### ISSUE TITLE
Transparency in Images

### ISSUE THREAD

**Issue by peter-ki** [yhatt/marp#171] opened 2017-04-05 15:11 UTC
PNG's get a white background so transparency in it is not transparent. If you use images in slides with a background, this can be disturbing.

**Comment by hholst80** [comment] 2018-01-15 13:47
What do you mean? You probably have rendered your PNGs with a white background instead of a transparent background?

**Comment by Rakhmanov** [comment] 2018-08-01 21:59
Duplicate of #119

**Comment by yhatt** [comment] 2018-10-07 17:32
We're making a clean sweep of piled up issues. https://github.com/yhatt/marp/issues/119#issuecomment-409743232 has a workaround for current Marp.

**Closed by yhatt** 2018-10-07 17:32 UTC
Labels: Supports in Marp Next, duplicate
