### ISSUE TITLE
Directly export as `markdown`?

### ISSUE THREAD

**Issue by fduxiao** [yhatt/marp#247] opened 2018-10-21 12:39 UTC
I've noticed that there's a `markdown` preview style, which won't split the markdown into slides. Sometimes I do want to export just plain markdown as is previewed in the `markdown` style, since you know your editor is wonderful and I think Marp could be a suitable markdown editor to me if I could export it directly.

**Comment by yhatt** [comment] 2018-10-21 16:14
Duplicate of #4.

Currently we have not focused to Markdown view, for preventing scope creep of our projects. We suggest the maintained tools or plugins. (e.g. Markdown PDF plugin for [VSCode](https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf), [Atom](https://atom.io/packages/markdown-pdf))

**Closed by yhatt** 2018-10-21 16:14 UTC
Labels: duplicate
