### ISSUE TITLE
Table render problems

### ISSUE THREAD

**Issue by pnizet** [yhatt/marp#128] opened 2016-11-17 15:47 UTC
When rendering a pdf the upper line of the table is repeated on top of the slide :

![bug_table](https://cloud.githubusercontent.com/assets/8044949/20396113/6c0f9de4-ace5-11e6-93e6-b5ee92cee965.png)

**Comment by yarray** [comment] 2016-11-21 01:56
Possible duplicate of #101 ?

**Comment by pnizet** [comment] 2016-11-21 08:22
indeed. Sorry for haven't seen #101 
You can close it

**Closed** 2016-11-29 10:31 UTC
