### ISSUE TITLE
How to start a presentation mode?

### ISSUE THREAD

**Issue by cookiengineer** [yhatt/marp#38] opened 2016-07-15 22:36 UTC
I can't find something in the UI to actually present the written slides.
How can I get into presentation mode?

Rather than that everything seems to be awesome ^_^

**Comment by wb9688** [comment] 2016-07-16 04:57
There is no presentation mode yet, so this is a duplicate of #13.

**Comment by yhatt** [comment] 2016-07-16 05:29
Merge to #13.

**Closed by yhatt** 2016-07-16 05:29 UTC
Labels: duplicate
