### ISSUE TITLE
Image missing on PDF Export

### ISSUE THREAD

**Issue by Beomi** [yhatt/marp#108] opened 2016-10-22 08:32 UTC
Hello, I've tried to export document with some images.
When I write down document with preview, it seems like works nomally.
however, when I try to export document with PDF, some images are missing at all.
you can check my .md file at [here](https://gist.github.com/Beomi/23e35e2793e0d89a0a05bb8aab64cfe2)
I hope it fixed soon :)

**Comment by yhatt** [comment] 2016-11-01 12:13
Thanks for your reporting.
Certainly the preview is working correctly. And CSS styling for exporting PDF seems having no problem. So it is most likely to be caused by PDF renderer (Chromium).

**Comment by yhatt** [comment] 2016-11-01 12:16
FYI: Currently you can avoid this issue by trying not to protrude image size from each slide.

**Comment by yhatt** [comment] 2019-06-04 11:57
It has already resolved in Marp Next.

**Closed by yhatt** 2019-06-04 11:57 UTC
Labels: Supports in Marp Next, bug
