### ISSUE TITLE
Features desperately needed: Dark theme, and automatic scrolling

### ISSUE THREAD

**Issue by dessalines** [yhatt/marp#138] opened 2016-12-14 22:38 UTC
Nearly all online markdown editors have these.

**Comment by will-hart** [comment] 2016-12-15 08:13
Duplicate of #117 and #24.

Dark theme do you mean for the editor or the slides? If the slides, duplicate of #115, #5 and #1

**Comment by dessalines** [comment] 2016-12-15 15:57
Dark theme for the entire app, but primarily the editor window and the markdown view.

**Comment by Naereen** [comment] 2017-02-17 08:41
@yhatt any update?

**Comment by yhatt** [comment] 2018-10-14 08:38
We've splited out issues to focus one topic per issue. Refer to #245 about dark theme.

As he already pointed out above, the other topics are duplicated issues.

**Closed by yhatt** 2018-10-14 08:38 UTC
Labels: duplicate

**Comment by Naereen** [comment] 2018-10-14 11:50
OK!
