### ISSUE TITLE
Sync markdown Edit/Rendering window

### ISSUE THREAD

**Issue by larabih** [yhatt/marp#117] opened 2016-11-03 10:03 UTC
It is possible to add the synchronisation option to Marp in objectif to sync Edit window with Render window : 
 * By scrolling the editing pane the rendering pane move with it.
 * To simplify search, like as TeXShop  _forward-inverse-search_  **`cmd + right click`**

**Comment by will-hart** [comment] 2016-11-04 07:02
Duplicate of #24?

**Comment by yhatt** [comment] 2018-10-14 08:13
We're making a clean sweep of piled up issues. It is a duplicated issue with #24.

**Closed by yhatt** 2018-10-14 08:13 UTC
Labels: duplicate
