### ISSUE TITLE
Support custom CSS class

### ISSUE THREAD

**Issue by mathieubrochard** [yhatt/marp#115] opened 2016-11-01 14:17 UTC
Is it possible to add a custom CSS classes to elements ?

Example:

```
<style>
.image {
    border: 1px solid black;
}

.image.right {
    float: right;
}
</style>

![A junk image](junk.png){.image .right}
```

**Comment by will-hart** [comment] 2016-11-04 07:00
Duplicate of #1

**Comment by mathieubrochard** [comment] 2016-11-04 09:23
Woops, sorry!

**Comment by will-hart** [comment] 2016-11-04 12:13
NP, it might be worth closing the issue to keep the issue tracker clear.

**Comment by yhatt** [comment] 2018-10-07 18:15
I thought that it is duplicated issue about the class of slide too (and Marp Next is supported `class` directive), but actually it was not correct.

A feature that is needed in this issue is an ability to specify class to element of Markdown contents. #1 says about CSS theming support.

However, we don't really want to extend markdown syntax like `![](image){.class}`. Marp Markdown aims to keep a compatibillity with CommonMark. (See #87)

By using modulized projects in [Marp Next](https://github.com/marp-team/marp), you can extend with [markdown-it-attrs](https://www.npmjs.com/package/markdown-it-attrs) plugin if *you want*.

**Closed by yhatt** 2018-10-07 18:15 UTC
