### ISSUE TITLE
 When you open the PDF, when you try to override, can not be control.

### ISSUE THREAD

**Issue by daijinload** [yhatt/marp#94] opened 2016-10-03 08:16 UTC
My PC is Windows7.
It is not a critical.
I can be closed using the Task Manager.

**Comment by yhatt** [comment] 2016-10-08 09:57
Thank you reporting. This issue is also occurred in my Windows 10 when I had opened PDF file in the other process (e.g. Adobe Reader).

Currently Marp can't detect file locking state. I would keep investigating the cause...

**Comment by daijinload** [comment] 2016-10-08 19:51
Thanks for watching.

I created eletctron [test-project](https://github.com/daijinload/electron-test) in my repository.
printToPDF error handling is correctly moving.
Please look at your error handling.

**Comment by yhatt** [comment] 2016-11-01 10:36
Oh, I know. Marp's error handling is not correctly.
We would fix it as to show dialog when saving to locked file.

**Comment by yhatt** [comment] 2016-11-06 09:02
We merged #113. Marp v0.0.10 (as known as v0.0.9.1) is going to release soon.

**Closed** 2016-11-06 09:58 UTC
Labels: bug, Windows
