### ISSUE TITLE
Presentation mode?

### ISSUE THREAD

**Issue by orschiro** [yhatt/marp#107] opened 2016-10-20 06:12 UTC
Dear @yhatt and others, 

Instead of having to export a presentation to PDF, open it with a PDF viewer and start the presentation, how about Marp directly featuring a full-screen presentation mode?

Thanks!

:smile:

**Comment by Sathors** [comment] 2016-10-20 22:00
Seems to me like a duplicate of #13.

**Closed** 2016-10-21 05:36 UTC

**Comment by orschiro** [comment] 2016-10-25 18:32
Thanks!
