### ISSUE TITLE
Command line tool to convert markdown files to slide pdf

### ISSUE THREAD

**Issue by eruvanos** [yhatt/marp#164] opened 2017-03-15 10:09 UTC
I want to store the source file in an repository and publish the newest version via a commit triggering an CI instance.

A command line tool for at least linux would be nice, that takes the source file and produces the PDF, like the export functionality.

**Comment by will-hart** [comment] 2017-03-15 23:18
Duplicate of #50

**Closed** 2018-08-23 11:02 UTC
Labels: Supports in Marp Next, duplicate
