### ISSUE TITLE
Externally edited background images not updated in preview

### ISSUE THREAD

**Issue by kakyoism** [yhatt/marp#147] opened 2017-02-04 18:43 UTC
I'm on 0.0.10.

**Observations:**

- If the image is edited using external tools, in Marp app's preview, the image still looks the same as the previous version.
- If I remove the `![bg](images/my.png) ` code, the image will disappear in preview (expected); but it will look the same as before after adding the code back (unexpected).
- The image is only updated after reopening Marp app.

**Expected:**

 - The image in preview should be synced to image, at least after performing a removing/adding-back cycle of the image code.

**Comment by will-hart** [comment] 2017-02-04 21:13
Duplicate of #56?

**Comment by yhatt** [comment] 2018-09-16 15:49
We're making a clean sweep of piled up issues. This issue is duplicated of #56.

**Closed by yhatt** 2018-09-16 15:49 UTC
Labels: duplicate
