### ISSUE TITLE
UTF-8 encoding is buggy

### ISSUE THREAD

**Issue by fpg1503** [yhatt/marp#59] opened 2016-07-27 04:26 UTC
It is not possible to save/open files with text using accents, the encoding is almost always wrong.

For instance: if you write `Acentos não funcionam` to a file and save it when you open it again it will read `Acentos n達o funcionam`.

**Comment by yhatt** [comment] 2016-07-30 12:37
Thanks. It has already reported in #22 and we had tried to fix it in another way (#53).

This issue have caused by the [jschardet](https://github.com/aadsm/jschardet)'s encoding detection.
In next version `v0.0.9`, the feature of reopening with specified encoding would be able to help it.

So we marked `wontfix`. I would report this issue to jschardet if we received too many similar issues.

**Closed by yhatt** 2016-07-30 12:37 UTC
Labels: duplicate, wontfix

**Comment by miestasmia** [comment] 2017-11-07 09:06
It seems odd to me that it doesn't open with UTF-8 by default, or even make an attempt to recognize the character encoding. [There's even an npm package for it](https://www.npmjs.com/package/detect-encoding).

**Comment by maxlevesque** [comment] 2018-09-11 09:13
Hi there it's still buggy in 0.0.13. Tanks anyway Marp is very useful. :)
